# Generated by Django 5.2.12 on 2026-04-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_processor", "0013_add_last_picked_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringtask",
            name="trace_context",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="trace_context",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
