# Minimal dependencies to run Flagsmith non-Dockerized, including its test
# suite. Currently, settings are analogous to CI for compatibility.

# TODO: Use Docker Compose in CI to run tests.

name: flagsmith

volumes:
  default-database:
  task-processor-database:

services:
  default-database:
    image: postgres:15.5-alpine
    restart: unless-stopped
    volumes:
      - default-database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: pg_isready -Upostgres
      interval: 1s
      timeout: 30s

  task-processor-database:
    image: postgres:15.5-alpine
    restart: unless-stopped
    volumes:
      - task-processor-database:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: pg_isready -Upostgres
      interval: 1s
      timeout: 30s
