# A Compose file with minimal dependencies to be able to run Flagsmith, including its test suite, locally (not in Docker).

name: flagsmith

volumes:
  pg_data:
  task_processor_pg_data:

services:
  db:
    image: postgres:15.5-alpine
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: flagsmith
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -Upostgres
      interval: 1s
      timeout: 30s

  task-processor-db:
    image: postgres:15.5-alpine
    restart: unless-stopped
    volumes:
      - task_processor_pg_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: pg_isready -Upostgres
      interval: 1s
      timeout: 30s
