name: Python Typing and Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Linting and Formatting

    steps:
      - name: Cloning repo
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: poetry install --with dev

      - name: Check for missing migrations
        run: poetry run python manage.py makemigrations --no-input --dry-run --check

      - name: Check for new typing errors
        run: poetry run mypy .

      - name: Run Tests
        run: poetry run pytest
